sudo: required
services:
  - docker

script:
#    - docker build --tag dina/collections-solr:$TRAVIS_TAG .
    - docker build --tag dina/collections-solr .
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push dina/collections-solr
